name: Build
on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set yarn version
        run: yarn set version 1.22.10
      - name: Install Dependencies
        run: yarn install
      - name: Run Test
        run: yarn test:coverage
      - name: Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
